### ISSUE TITLE
Listen to clippy >:(

### ISSUE THREAD

**Issue by airidaceae** [hearth-rs/hearth#108]
@marceline-cramer Clippy is doing its best. It really wants Hearth to succeed. Honestly? probably more than you do. make! Clippy! happy! follow its advice

**Comment by marceline-cramer** [comment]
i'm sorry Clippy, i promise i'll do better from now on 🥺

**Comment by marceline-cramer** [comment]
Since clippy passes in main now and since PR merges are forbidden unless they pass too, I'm going to call clippy listened to for now. #178 addresses some minor warnings but yeah.

**Comment by airidaceae** [comment]
clippy is so happy right now. jumping up and down. running around in circles, waving hands excitedly. talking about how excited it is for hearth's beta stage. clippy is so proud of you marceline. you have done an amazing job.
