### ISSUE TITLE
github: rustfmt Github action is broken again

### ISSUE THREAD

**Issue by airidaceae** [hearth-rs/hearth#110]
different issue than in #2 
```
Run LoliGothick/rustfmt-check@master
Executing cargo fmt (JSON output)
Error: Error: Rustfmt had exited with the Exit Code 1:
Failed to find targets
cargo-fmt 
```
It seems like the action is out of date and needs to be updated. Im not too familiar with github actions so thats just a guess.

**Comment by marceline-cramer** [comment]
It's pulling the master branch, so there's nothing we can do about it from here. We either need to wait until it's updated by the maintainer upstream, make our own PR to update it, or disable rustfmt again until it works.
