### ISSUE TITLE
types: impl `Display` for `ProcessId`

### ISSUE THREAD

**Issue by marceline-cramer** [hearth-rs/hearth#118]
Let's come up with a human-readable formatting convention for global process IDs, then implement `Display` for `ProcessId` to actually print them. @airidaceae may have input.

My suggestion is `(<peer-id>, <local-pid>)`, but `<peer-id>, <local-pid>` may be easier to type if we wanted user input for these too.

**Comment by airidaceae** [comment]
what about `<peer-id>.<local-pid>`?

**Comment by marceline-cramer** [comment]
I love it, do it.
