### ISSUE TITLE
guest: implement custom panic handler

### ISSUE THREAD

**Issue by marceline-cramer** [hearth-rs/hearth#128]
Implement a custom panic handler in the `hearth-guest` crate to log panic messages to the Hearth process log: https://doc.rust-lang.org/nomicon/panic-handler.html.

**Comment by marceline-cramer** [comment]
This is hard to do because the `#[panic_handler]` attribute only works in `#[no_std]` environments. We'd need to somehow override the panic handler before any guest-side code runs.

For indexed entrypoints (ones spawned by the module itself, which has access to those indices), that's pretty simple because there's a wrapper function that can set the panic handler. However, the raw, exported `run` function should also be able to do this automatically.

@emmatebibyte, do you know of a way to set a custom panic handler without having to call https://doc.rust-lang.org/std/panic/fn.set_hook.html manually?

**Comment by emmatebibyte** [comment]
Relevant issue: https://github.com/rust-lang/rust/issues/59222

**Comment by marceline-cramer** [comment]
I have a solution: export an `init` function from `hearth-guest` that the runtime always calls before it invokes either the `run` function or indexed entrypoints.
