### ISSUE TITLE
Get rid of PeerId

### ISSUE THREAD

**Issue by marceline-cramer** [hearth-rs/hearth#143]
`hearth-types` had a `PeerId` type that was used in the old remoc-based RPC code, but because we currently don't have identifiers for peers, `PeerId` is useless and should be purged. Same with `ProcessId` (but not `LocalProcessId`).

This will affect the core code (`PeerId` is used in `RuntimeConfig`), the server, and the client.

**Comment by airidaceae** [comment]
Since peer ids are gone should we rename `LocalProcessId` to just `ProcessId`?

**Comment by marceline-cramer** [comment]
Yeah, they're semantically different, so it won't cause any side effects.

If we add global process IDs back in for debugging purposes we could make a new `GlobalProcessId` or something.
