### ISSUE TITLE
fs: handle and return errors appropriately

### ISSUE THREAD

**Issue by marceline-cramer** [hearth-rs/hearth#144]
`hearth-fs` performs file operations, most of which can fail. `hearth-types` defines the `fs` protocol, which includes a `Response` type that may contain errors. Right now, `hearth-fs` simply panics when any errors occur. We need to catch those errors and safely map them to `Response`s, adding more if necessary.

**Comment by airidaceae** [comment]
I'm interesting in potentially doing some work on this

**Comment by marceline-cramer** [comment]
> I'm interesting in potentially doing some work on this

sounds great, go for it!
