### ISSUE TITLE
server: app doesn't quit when interrupted

### ISSUE THREAD

**Issue by marceline-cramer** [hearth-rs/hearth#145]
My hunch for this is that there are Wasm processes that are not aborted when the runtime shuts down.  One blind and high-effort solution may be to make `hearth-wasm` abort all of its processes when it's dropped.

A better way to approach this would be to use [this](https://github.com/tokio-rs/console) and find out which processes are lingering.

Another way would be to manually create and then drop a Tokio runtime so that ALL green threads are properly dropped.

**Comment by marceline-cramer** [comment]
We may want to integrate this into the `Runtime` API:
https://docs.rs/tokio-utils/latest/tokio_utils/struct.ShutdownController.html

**Comment by marceline-cramer** [comment]
One way to help manage this would be to make the shutdown of the runtime close all of the route groups for all local processes. That way, all Tokio threads that are receiving from process mailboxes would be closed automatically without any intervention from another synchronization component.

**Comment by airidaceae** [comment]
I'm not sure how to replicate this.

**Comment by marceline-cramer** [comment]
Yeah, I've tried this too and it seems like this doesn't happen anymore. Let's close it for now and if it pops up again, we can just reopen it.
