### ISSUE TITLE
rend3-alacritty: demo retains $TERM and other undesirable variables from the parent process 

### ISSUE THREAD

**Issue by siltyy** [hearth-rs/hearth#173]
Running `echo $TERM` in the demo for rend3-alacritty yields the unmodified `$TERM` variable from the process that ran the demo. It's fine and expected that inherited environment variables are retained, but given the nature of the application, it makes sense to override some of them. At the very least, `TERM`, `COLORTERM`, and `terminfo` should be overridden, and potentially `termcap` (I am unsure if this gets set already, but it's safe to assume that it doesn't).

The question is, though, what *should* they get set to? #172 shows that simply copying everything over from alacritty would *currently* be lying to applications, but perhaps the  goal should be to replicate alacritty's behavior to such a degree that simply using its terminfo would be accurate. What, really, is the issue here? Is it that we don't conform to alacritty's terminfo, etc., or that we don't provide our own? This question becomes more pressing around the topic of image support. Alacritty does not currently support any image protocols, and its [SIXEL pull request](https://github.com/alacritty/alacritty/pull/4763) seems dead in the water right now. If we commit to conforming to alacritty's terminfo, then we're bound to whatever happens with that PR and also unable to implement a different image protocol if something other than SIXEL (such as Kitty) is desired.

**Comment by marceline-cramer** [comment]
Since #172 is resolved, would we still be lying to applications by duplicating Alacritty's behavior?

**Comment by siltyy** [comment]
If we can extrapolate from #172 that whatever few differences that exist are treated as bugs and get fixed upstream, then no it wouldn't be lying to just go ahead and duplicate Alacritty's behavior regarding environment variables.

**Comment by marceline-cramer** [comment]
@siltyy This is my fault for not asking a more straight-forward question but to be clear is using the Alacritty `setup_env` function I linked sufficient to close this issue?

**Comment by siltyy** [comment]
Yeah, it should be sufficient, though you might want to also add a note about ensuring that Alacritty's terminfo is present for full terminal functionality. It seems to ship by default with ncurses these days, but systems that aren't on the bleeding edge may be stuck without that for a while, depending on the distro's update schedule. Windows users are also a thing and they should probably know about it.
