### ISSUE TITLE
client: server DNS address resolution

### ISSUE THREAD

**Issue by marceline-cramer** [hearth-rs/hearth#18]
Add support to clients to connect to servers by their hostnames.

We'll need to replace the `SocketAddr` in `Args` with a `String`, then first attempt to parse it to an IP address, and if that fails, try looking up the DNS. We can use [trust-dns-resolver](https://crates.io/crates/trust-dns-resolver) to look up hostnames.

If parsing out the port is too complicated to do in conjunction with parsing hostnames/IPs, we can move the port into a different argument. In that case, we should adjust the server to take the port separately as well.

If parsing fails, please fail nicely with good error messages!

DNS resolution isn't necessary on servers, as far as I know, because most of the time we'll just be binding to a fixed IP.

**Comment by airidaceae** [comment]
The standard library has a DNS resolver with `std::net::ToSocketAddrs` which resolves using the host systems resolver. 

https://docs.rs/trust-dns-resolver/0.22.0/trust_dns_resolver/
"This is a 100% in process DNS resolver. It does not use the Host OS’ resolver. If what is desired is to use the Host OS’ resolver, generally in the system’s libc, then the std::net::ToSocketAddrs variant over &str should be used." 

I think its probably best for us to stick with the standard library unless there is some specific reason to resolve things differently than the host system wants.

**Comment by marceline-cramer** [comment]
@airidaceae No, let's go with the standard library. I went with that crate because reqwest depends on it and it has a lot of downloads. Good catch!
