### ISSUE TITLE
Reorganize repository

### ISSUE THREAD

**Issue by airidaceae** [hearth-rs/hearth#199]
Currently everything is store inside of the crates directory which can be a bit daunting and confusing. After #188 and #169, we should move `hearth-ctl`, `hearth-core`, `hearth-server`, `hearth-client`, and `hearth-types` to the root of the repository. We should then rename the `crates` directory to plugins.

**Comment by airidaceae** [comment]
I'm going to link all related issues here for ease of access.
#188 
#169 
#200
#167

**Comment by marceline-cramer** [comment]
Oh yeah, `hearth-ipc` is also not a plugin. Maybe we should have shared crates (`core`, `types`/`schema`, `ipc`) in one subdirectory, and binaries in another subdirectory?

**Comment by airidaceae** [comment]
maybe. I think an important part of this is getting the big chunks of the important code (namely core) into an accessible part of the repository.

**Comment by airidaceae** [comment]
for me sub-directories depends entirely on what we come up with for names.

**Comment by marceline-cramer** [comment]
What I'm thinking right now is:
- `shared`: `types`, `core`, `ipc`
- `plugins`: plugins
- `apps` or `binaries` or something: `client`, `server`, `ctl`

**Comment by airidaceae** [comment]
latest plan for this is as follows
```
- plugins/
  ... fs, wasm, daemon ...
- apps/
  ... client, server, ctl ...
- core/
  ... schema, ipc, runtime ...
- guest/
  ... rust/guest, grain/guest, assemblyscript/guest ...
- kindling/
  ... common, init, build, physics, panel manager, glTF ...
  ```
