### ISSUE TITLE
Downgrade clap v4 to v3 in all binary targets

### ISSUE THREAD

**Issue by marceline-cramer** [hearth-rs/hearth#20]
I personally disagree with the clap developers' decision to change the theming of `--help` docs from these nice colored sections to monochrome text: https://github.com/clap-rs/clap/issues/4132. I think that this hurts readability, and that strong color-coding will be important in Hearth when running `hearth-ctl` while in-space.

This unfortunately can't be reverted in clap v4. The clap devs may add in styling for docs in the future, but the future is not now. However, the [structopt crate](https://crates/crates/structopt) provides the same procedural macro-based argument parsing, but on clap v3, which has the old colored output.

Downgrading from clap v4 to clap v3 won't have any serious consequences on the argument parsing itself, so it's not like we're sacrificing features for this. However, if anyone prefers the uncolored clap v4 output over the colored clap v3 output, please pitch in your opinion in this issue so that we can discuss it more.

For now, I'm using clap v4 in #19.

If we do decide to use structopt, clap v4 will need to replaced in three of our crates:
- `hearth-client`
- `hearth-server`
- `hearth-ctl`

**Comment by MalekiRe** [comment]
I prefer colored output

**Comment by airidaceae** [comment]
I'm completely fine with either. I can certainly see the colored output making it look more approachable and easy to use.

**Comment by marceline-cramer** [comment]
Alright, this is open for solving then.

**Comment by marceline-cramer** [comment]
As it turns out clap v3 also has a derive macro. No need to use structopt!
