### ISSUE TITLE
Matrix room invite not working

### ISSUE THREAD

**Issue by squeaktoy** [hearth-rs/hearth#255]
The server leyline.witchcraft.zone cannot be reached.

**Comment by squeaktoy** [comment]
I can actually visit leyline.witchcraft.zone from my web browser, but trying to join the #hearth:leyline.witchcraft.zone room fails on any of my Matrix accounts.

**Comment by squeaktoy** [comment]
leyline.witchcraft.zone seems to return 200 for any HTTP request made. Even stuff like https://matrix.leyline.witchcraft.zone/_synapse/admin/v1/server_version returns nothing useful.

**Comment by airidaceae** [comment]
Theres also an issue with the bridge at the moment that I was working on resolving when things went down. I should be able to fix them both around the same time hopefully. Ill ping you when they are fixed.

**Comment by airidaceae** [comment]
@squeaktoy We should be good to go! Please close the issue if things are working for you :)

**Comment by squeaktoy** [comment]
I can connect to the server now and I joined the Hearth space, there are no rooms to join. There's only the space, but no rooms :/

**Comment by airidaceae** [comment]
Odd. I will look into it. You could join the rooms directly in the meantime at #hearth-general and hearth-dev
