### ISSUE TITLE
Does the crypotography check out?

### ISSUE THREAD

**Issue by marceline-cramer** [hearth-rs/hearth#8]
Dammit Jim, I'm a graphics programmer, not a cryptographer!

I'm not sure if the makeshift authentication and encryption protocol I've whipped up in #5 has good enough security. At the time of writing this, there is zero chance that anyone will try to make an attack, but in the future when Hearth is more popular, it may be possible. Here are some specific things I'm worried about as someone who knows nothing about cryptography:

1. The IV is always zero, even though the session key is different every time. Is that an issue?
2. The same IV is used for the entire lifetime of communication. ChaCha20 has a 92-bit IV so it shouldn't be exhausted in practice, but is that still something to worry about?
3. Server-to-client and client-to-server communication use the same key and IV after PAKE. An observer could XOR their histories together to get the ChaCha20 keystream. Is that something to worry about?

There are probably more potential security issues that I haven't thought of, so if you're reading this and you know anything about cryptography, please help us out!

**Comment by akamicah** [comment]
I'm no expert but if your IV is always zero then I do believe if you encrypt the same message twice the output will be identical, which leads to a bad actor being able to distinguish encryptions
IV in CBC should be unpredictable, using cryptographic random number generation

More info:

https://www.techtarget.com/whatis/definition/initialization-vector-IV

"The ideal IV is a random or pseudorandom number. It must also be nonrepeating. Both randomness and nonrepetitiveness are crucial to prevent attackers from finding patterns in similar parts of the encrypted message and then using this information to decrypt the message.

The IV need not be secret. In fact, the destination computer usually knows the IV so it can decrypt the encrypted data when it receives it. Thus, the IV would be agreed on in advance by both the sender and the recipient. In addition, the IV can be transmitted independently or included as part of the session setup prior to message exchange."

**Comment by marceline-cramer** [comment]
Alright, I can use the other 32 bits I'm discarding from OPAQUE's 64-bit key for the IV and set the other 64 bits to zero. The 32-bit encryption key is entirely from the OPAQUE key, but there's another 32 bits I can utilize.

Thank you for the input.

**Comment by marceline-cramer** [comment]
My bad, OPAQUE actually returns a 64-***byte*** array, not a 64-bit array. ChaCha20 also uses a 32-***byte*** key.

The IV can be completely random because we have more than enough random bytes from OPAQUE.

**Comment by marceline-cramer** [comment]
Closed in favor of TLS in #163.
