### ISSUE TITLE
readme: add subdomain hosting to release phase of roadmap

### ISSUE THREAD

**Issue by airidaceae** [hearth-rs/hearth#82]

**Comment by airidaceae** [comment]
We've been thinking about this more and we feel it would be best to change this now rather than later. To change this, and by extension support reverse proxies, we would have to change to a protocol that reverse proxies understand. For our purposes the only real option is WebSockets.

**Comment by marceline-cramer** [comment]
I'll open a new issue for WebSockets and add it to the roadmap in pre-alpha.
